import React, { useState } from "react";
import axios from "axios";
import { Link } from "react-router";

const Signup = () => {
  const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [phone, setPhone] = useState(""); const [isSeller, setIsSeller] = useState(false); const [loading, setLoading] = useState(false);
  const signUp = async (e) => { e.preventDefault(); setLoading(true); try { const result = await axios.post("/api/v1/signup", { firstName, lastName, email, password, phone, isSeller }); alert(result.data.message); } catch (error) { alert(error.response?.data?.message || "Something went wrong"); } finally { setLoading(false); } };
  return <main className="center-page"><section className="card auth-card"><div className="logo">Ecom Store</div><h1>Create account</h1><p className="subtext">Fill in your details to get started</p><form onSubmit={signUp}><div className="input-row"><label>First name<input required value={firstName} onChange={(e) => setFirstName(e.target.value)} /></label><label>Last name<input required value={lastName} onChange={(e) => setLastName(e.target.value)} /></label></div><label>Email address<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Enter your email" /></label><label>Password<input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Create a password" /></label><label>Phone number<input required value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="03XX XXX XXXX" /></label><label className="checkbox"><input type="checkbox" checked={isSeller} onChange={(e) => setIsSeller(e.target.checked)} />Signup as Seller</label><button disabled={loading}>{loading ? "Creating account..." : "Signup"}</button></form><p className="switch-text">Already have an account? <Link to="/login">Login</Link></p></section></main>;
};
export default Signup;
